clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  vue-build-check:
    image: node
    commands:
     - ./tests/vue-build.sh ./js/notifications.js
    when:
      matrix:
        TESTS: vue-build-check
matrix:
  include:
    - TESTS: vue-build-check
